# Generated by Django 5.0 on 2023-12-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_myuser_managers_remove_myuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
